#!/bin/bash

CURRENT_SCRIPT_DIR_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
PROJECT_DIR_PATH="$(cd "$CURRENT_SCRIPT_DIR_PATH/.." && pwd)"
source "$CURRENT_SCRIPT_DIR_PATH/lib/merge.bash"
source "$CURRENT_SCRIPT_DIR_PATH/lib/commons.bash"
source "$CURRENT_SCRIPT_DIR_PATH/lib/git.bash"
cd "$PROJECT_DIR_PATH"

MESSAGE=""
YES=0

_processHelp "$@"
_loadArgs "$@"

_merge